data=csvread("./build/mandel.dat");
outdata=data(:,1);
indata=data(:,2);
outdata(outdata==max(outdata))=0;
outdata=outdata/max(outdata);
indata(indata>4.0)=4;
indata(outdata!=0)=4;
indata=sqrt(indata)/2;
zdata = min(indata,log(outdata)/2+1);
zmat = flipud(reshape(zdata,sqrt(size(zdata,1))*[1,1]));
imwrite(zmat,"./build/test.png");
